apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  #googleCloudBuild:
    #projectId: ticketing-dev-289021
  artifacts:
     - image: 091994/auth-ticketing
       context: auth
       docker:
         dockerfile: Dockerfile
       sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
     - image: 091994/client-next
       context: client
       docker:
         dockerfile: Dockerfile
       sync:
        manual:
          - src: '**/*.js'
            dest: .
     - image: 091994/tickets
       context: ticket
       docker:
         dockerfile: Dockerfile
       sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
     - image: 091994/orders
       context: orders
       docker:
         dockerfile: Dockerfile
       sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
